# Copyright (c) 2012-2016 Codenvy, S.A., Red Hat, Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#   Codenvy, S.A. - initial API and implementation
#   Mario Loriedo
#
# To build, in this directory:
#  docker build -t registry.centos.org/codenvy/che-dev -f Dockerfile.centos .
#
# Use it to Build Che using Docker on Linux or Mac. Run int the repository root:
#   docker run -it --rm --name build-che
#              -v "$HOME/.m2:/home/user/.m2"
#              -v "$PWD":/home/user/che-build
#              -w /home/user/che-build
#              registry.centos.org/eclipse/che-dev
#              mvn -DskipTests=true
#                  -Dfindbugs.skip=true
#                  -Dgwt.compiler.localWorkers=2 -T 1C
#                  -Dskip-validate-sources
#              clean install
#
# For Windows, replace $HOME with maven repo directory.
# For Windows, replace $PWD with Che source code directory.

FROM codenvy/centos_jdk8
# ENV NODE_VERSION=0.12.9 \
#     NODE_PATH=/usr/local/lib/node_modules

RUN sudo yum -y update && \
    sudo yum -y install @"Development Tools" && \
    sudo yum -y install centos-release-scl openssl-devel krb5-devel gcc make ruby ruby-devel rubygems golang && \
    sudo yum -y install rh-nodejs4 && \
    sudo gem install sass compass && \
    sudo yum clean all 

EXPOSE 3000 5000 9000
RUN sudo scl enable rh-nodejs4 'npm install -g npm@latest'
RUN sudo scl enable rh-nodejs4 'npm install --unsafe-perm -g gulp bower'
RUN mkdir ~/gopath 
    # sudo tar -xvf go1.6.2.linux-amd64.tar.gz -C /opt/ && \
    # rm go1.6.2.linux-amd64.tar.gz
ENV GOROOT=/usr/bin/go
ENV GOPATH=/home/user/gopath
RUN echo "export PATH=$GOROOT/bin:$PATH" >> ~/.bashrc

WORKDIR /home/user
